--- 
steps: 
  - 
    args: 
      - functions
      - deploy
      - 
        - runtime=Python 3.9
        - trigger-http
        - source=./
        - entry-point=helloCiCd
      - helloCiCd
    name: 'gcr.io/cloud-builders/gcloud'
